# Run whenever a push/merge is done
# to the develop branch
name: Deploy develop merge/push
on:
  push:
    branches:
      - main

env:
  DOCKER_TAG: '0.0'
  ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'

jobs:
  code-validations:
    name: Run validations
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install packages
        run: yarn install

  bump-version:
    name: 'Bump version on develop'
    needs: code-validations
    runs-on: ubuntu-latest
    outputs:
      newTag: ${{ steps.check_docker_tag.outputs.newTag}}
      dockerTag: ${{ steps.check_docker_tag.outputs.DOCKER_TAG}}
    steps:
      - name: 'Checkout source code'
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - name: 'cat package.json'
        run: cat ./package.json
      - name: 'Automated Version Bump'
        id: version-bump
        uses: 'phips28/gh-action-bump-version@master'
        with:
          tag-prefix: 'v'
          commit-message: 'ci: bumps dev version to {{version}} and deploy 📦 '
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: 'cat package.json'
        run: cat ./package.json
      - name: 'Output Step'
        env:
          NEW_TAG: ${{ steps.version-bump.outputs.newTag }}
        run: echo "new tag $NEW_TAG"
      - name: Change DOCKER_TAG env
#        run: echo "::set-env name=DOCKER_TAG::${{ steps.version-bump.outputs.newTag }}"
        run: echo "dockerTag=${{ steps.version-bump.outputs.newTag }}" >> $GITHUB_OUTPUT
      - id: check_docker_tag
#        run: echo "::set-output name=newTag::${{ env.DOCKER_TAG }}"
        run: echo "newTag=${{ env.DOCKER_TAG }}" >> $GITHUB_OUTPUT


  deploy:
    name: Deploy version
    runs-on: ubuntu-latest
    needs: bump-version
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: check newTag env
        run: echo "${{ needs.bump-version.outputs.newTag }}"

      - name: check dockerTag env
        run: echo "${{ needs.bump-version.outputs.dockerTag }}"

